tasks:
    - before: gp env -e PATH="/usr/local/cargo/bin:$PATH"
    - init: echo $PATH && eval $(gp env -e) && ./install.sh
    - command: echo $PATH && ~/.cargo/bin/rustlings watch
image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
