tasks:
    - init: gp env -e PATH="/usr/local/cargo/bin:$PATH" && eval $(gp env -e) && /workspace/rustlings/install.sh
    - command: eval $(gp env -e) && /workspace/.cargo/bin/rustlings watch
image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
