tasks:
    - init: [ -x ~/.cargo/bin/rustlings ] && ~/.cargo/bin/rustlings watch || ./install.sh
image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
