tasks:
    - init: export PATH="/usr/local/cargo/bin:$PATH" && ./install.sh
    - command: ~/.cargo/bin/rustlings watch
image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
