[package]
name = "rustlings"
version = "4.7.1"
authors = ["mokou <mokou@fastmail.com>", "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Small exercises to get you used to reading and writing Rust code!"
documentation = "https://doc.rust-lang.org/rust-by-example/index.html"
repository = "https://github.com/rust-lang/rustlings"
homepage = "https://doc.rust-lang.org/rust-by-example/index.html"

[dependencies]
argh = "0.1"
indicatif = "0.16"
console = "0.15"
notify = "4.0"
toml = "0.5"
regex = "1.5"
serde= { version = "1.0", features = ["derive"] }

[[bin]]
name = "rustlings"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.1"
glob = "0.3.0"

[features]
exercises = []
