[package]
name = "tooling"
version = "0.1.0"
authors = ["The Rustlings Maintainers"]
edition = "2018"
publish = false

[dependencies]
glob = "0.3.0"
serde = { version = "1.0.112", feature = ["derive"] }
toml = "0.5.6"
